LINKDING_URL=https://linkding.example.com
LINKDING_TOKEN=your-token
# LINKMENU_LAUNCHER=walker --dmenu -p {prompt}
# LINKMENU_OPEN=xdg-open
# LINKMENU_COPY=wl-copy
# LINKMENU_INPUTAUTOMATIONTOOL=ydotool type --file -
# LINKMENU_COPY_ACTION_FIELD="copy"
# LINKMENU_OPEN_URL_ACTION_FIELD="open"
# LINKMENU_AUTOTYPE_ACTION_FIELD="type"
# LINKMENU_CACHE_FILE=$HOME/.cache/linkmenu/bookmarks.json
# LINKMENU_CONNECT_TIMEOUT=5000
